#%RAML 1.0
title: American Flights API

/flights:
  get:
    queryParameters:
      destination:
        required: false
        enum:
          - SFO
          - LAX
          - CLE
          - ABC
          - CDA

  post:

  /{ID}:
    get:
